In Python, a decorator is a special type of function that can be used to modify or enhance the behavior of another function without changing its source code. Decorators provide a way to wrap a function and execute some code before and/or after the wrapped function's execution. They provide a way to add additional functionality to functions without modifying their code directly. decorator usually called before the defination of a function.
There are 2 types of decorator:
1. Built in decorator: @staticmethod,@classmethod,@abstractclass and @property etc.
2. User defined decorator: they create according to our need.

In [2]:
def decorator_function(original_function):
    def wrapper_function():
        print("Before the function is called")
        original_function()
        print("After the function is called")
    return wrapper_function

@decorator_function
def hello():
    print("Hello, world!")
hello()

Before the function is called
Hello, world!
After the function is called


In [14]:
import time
def check_time(fun):
    def inner(*k):
        start=time.time()
        fun(*k)
        stop=time.time()
        print('time taken by:',fun.__name__ ,stop-start)
    return inner
@check_time
def fun():
    print(55+7530)
    time.sleep(2)
fun()

7585
time taken by: fun 2.0010955333709717


In [15]:
@check_time
def mul(a,b):
    print(a*b)
mul(5,4)
    

20
time taken by: mul 0.0


In [16]:
def check(data_type):
    def outer(fun):
        def inner(*args):
            if type(*args) == data_type:
                fun(*args)
            else:
                raise TypeError("ye datatype nhi chalega")
        return inner
    return outer
@check(int)
def square(num):
    print(num**2)
square(2)

4


In Python, a closure is a function object that has access to variables in its enclosing scope, even when the enclosing function has finished executing. It "remembers" the values of these variables and can still access them later. The interesting part is that even after the outer_function has finished executing and returned the inner_function, the inner_function still retains access to the variable x. This is what makes it a closure.
Characteristics of closures:

Data Encapsulation: Closures encapsulate the variables from their enclosing scope, binding them together with the function code that operates on them.

Access to Enclosing Scope: Closures have access to variables from their containing scope, including the scope of the outer function. This is possible because the closure carries the references to those variables.

In [4]:
def outer(x):
    def inner(y):
        print(x+y)
    return inner# it returns the inner as a closure.
h=outer(5)
h(5)
h(7)

10
12


Iterables:
An iterable is any object in Python that can be looped over or iterated upon. It provides a way to access its elements one at a time.To make an object iterable, it needs to implement the __iter__() method, which returns an iterator object.
Examples of built-in iterables include lists, strings, dictionaries, sets, etc. 

Iterator:
An iterator is any object in Python that allows the programmer to traverse through a sequence of data without having to store the entire data in the memory. It implements the __iter__() method (which returns itself) and the __next__() method.
which retrieves the next element from the stream. The __next__() method raises a StopIteration exception when there are no more elements to be returned. 

Iteration:
Iteration is the process of looping over the elements of an iterable or an iterator. It is typically done using a for loop in Python.
 When you use a for loop to iterate over an iterable, it automatically calls the iter() function to obtain an iterator, and then it repeatedly calls next() on the iterator until a StopIteration exception is raised.

In [7]:
L=[1,2,3,4]
iter(L)
next(L) #list is iterable not iterator

TypeError: 'list' object is not an iterator

In [23]:
class odd:
    def __init__(self):
        self.val=1
    def __iter__(self):
        return self
    def __next__(self):
        val=self.val
        self.val+=2
        return val
o=odd()
for i in o:
    print(next(o),end=' ')
    if o.val==21:
        break

3 7 11 15 19 

In [25]:
next(o)
next(o)

27

In [15]:
class iterable:
    def __init__(self,l):
        self.limit=l
        self.current=0
    def __iter__(self):
        return self
    def __next__(self):
        if self.current<=self.limit:
            even =self.current
            self.current+=2
            return even
        else:
            raise StopIteration
a=iterable(100)
for i in a:
    print(i,end=',')
            

0,2,4,6,8,10,12,14,16,18,20,22,24,26,28,30,32,34,36,38,40,42,44,46,48,50,52,54,56,58,60,62,64,66,68,70,72,74,76,78,80,82,84,86,88,90,92,94,96,98,100,

In [17]:
class iterator:
    def __init__(self,l):
        self.limit=l
        self.current=1
    def __iter__(self):
        return self
    def __next__(self):
        if self.current<=self.limit:
            odd=self.current
            self.current+=2
            return odd
        else:
            raise StopIteration
a=iterator(20)
for i in a:
    print(i)
        

1
3
5
7
9
11
13
15
17
19


In [16]:
class Square:
    def __init__(self,n):
        self.num=n
        self.current=0
    def __iter__(self):
        return self
    def __next__(self):
        if self.current<=self.num:
            self.current+=1
            return self.current**2
        else:
            raise StopIteration
square=Square(10)
for i in square:
    print(i)

1
4
9
16
25
36
49
64
81
100
121


Generators are a special type of iterator that are defined using a function and the yield keyword. A generator function returns an iterator object that can be iterated over. When a generator function is called, it doesn't execute the whole function at once; instead, it generates values on-the-fly and pauses its execution state between each yield statement.

A normal fn that returns a sequence will create the entire sequence in memory before returning the result.This can be a big blow to memory usage while the sequence is very large.
The Generator function is memory friendly it does not need to store all items in memory Rather it store only a single value at a time. 

In [2]:
def fib():
    a=0
    b=1
    while True:
        yield a
        a,b=b,a+b
my_generator=fib()

In [3]:
for _ in range(10):
    print(next(my_generator))

0
1
1
2
3
5
8
13
21
34


In [1]:
import sys
import time
def generator(n):
    start_time = time.time()
    for i in range(n):
        yield i
        stop_time = time.time()
        print('time by generator:',(stop_time-start_time))
l_start=time.time()
L=[i for i in range(100000)]
l_stop=time.time()
print('time by list:',l_stop-l_start)
gen=generator(1000000000000)
b=sys.getsizeof(L)
a=sys.getsizeof(gen)
print('List',b)
print('gen',a)

time by list: 0.004003286361694336
List 800984
gen 248


In [ ]:
#generator reverse the string
def rev(n):
    a=len(n)
    b=a
    for i in range(a):
        yield n[b-1]
        b-=1
gen=rev('Hello Arpit')
for i in gen:
    print(i)

Q1.Difference between yield and return.

Ans. Return: "Return" is a keyword used to exit a function and provide a value back to the caller. When a function encounters a "return" statement, it immediately terminates the function's execution and sends the specified value back to the caller. 
    
    Yield: "Yield" is a keyword used in the context of generators in some programming languages like Python. A generator is a special type of function that generates a sequence of values instead of returning a single value. When a generator encounters a "yield" statement, it pauses its execution, returns the specified value, and saves its current state. The next time the generator is called, it resumes from where it left off, continuing its execution from the "yield" statement onward.

In [10]:
def Transpose(mat):
    tmat=[[mat[j][i] for j in range(len(mat))] for i in range(len(mat[0]))]
    return tmat
import numpy as np
a=np.arange(1,16)
b=a.reshape(3,5)
print(b)
var=Transpose(b)
for r in var:
    print(r)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
[1, 6, 11]
[2, 7, 12]
[3, 8, 13]
[4, 9, 14]
[5, 10, 15]


In [11]:
#chain decorator
def decorator1(func):
    def wrapper(*args, **kwargs):
        print("Decorator 1 before function call")
        result = func(*args, **kwargs)
        print("Decorator 1 after function call")
        return result
    return wrapper

def decorator2(func):
    def wrapper(*args, **kwargs):
        print("Decorator 2 before function call")
        result = func(*args, **kwargs)
        print("Decorator 2 after function call")
        return result
    return wrapper

@decorator1
@decorator2
def my_function():
    print("Inside the function")

my_function()

Decorator 1 before function call
Decorator 2 before function call
Inside the function
Decorator 2 after function call
Decorator 1 after function call
